In [1]:
import librosa
import librosa.display
import os
import pyttsx3
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import cv2
import numpy as np
import joblib
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from skimage.filters import sobel
from skimage.feature import graycomatrix, graycoprops
from skimage.measure import shannon_entropy
import warnings
warnings.filterwarnings('ignore')

### STFT + MFCC

In [2]:
sampling_rate = 44100
n_fft = 2048
hop_length = 512
n_mfcc = 39

features = []

commands = ["one", "two", "three", "four", "five", "grab", "release"]
for command in commands:
    command_features = []

    for i in range(400):
        filename = f"C:/AWC_Dataset/audio_files_preprocessed/{command}/{command}_{i}.wav"

        print("Processing:", filename)

        audio, _ = librosa.load(filename, sr=sampling_rate)

        stft = np.abs(librosa.stft(audio, n_fft=n_fft, hop_length=hop_length))
        mfcc = librosa.feature.mfcc(S=librosa.power_to_db(stft), n_mfcc=n_mfcc)

        # Calculate the mean of each MFCC coefficient across all frames
        mfcc_mean = np.mean(mfcc, axis=1)

        command_features.append(mfcc_mean)

    features.append(command_features)

features = np.array(features)

n_samples = features.shape[0] * features.shape[1]
n_features = features.shape[2]
features = features.reshape((n_samples, n_features))

print(features.shape)

Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_0.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_1.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_2.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_3.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_4.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_5.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_6.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_7.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_8.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_9.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_10.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_11.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_12.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_13.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_14.wav
Proce

Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_125.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_126.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_127.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_128.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_129.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_130.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_131.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_132.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_133.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_134.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_135.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_136.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_137.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_138.wav
Processing: C:/AWC_Dataset/audio_files_preproces

Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_250.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_251.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_252.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_253.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_254.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_255.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_256.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_257.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_258.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_259.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_260.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_261.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_262.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_263.wav
Processing: C:/AWC_Dataset/audio_files_preproces

Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_371.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_372.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_373.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_374.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_375.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_376.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_377.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_378.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_379.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_380.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_381.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_382.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_383.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/one/one_384.wav
Processing: C:/AWC_Dataset/audio_files_preproces

Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_96.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_97.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_98.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_99.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_100.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_101.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_102.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_103.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_104.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_105.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_106.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_107.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_108.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_109.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/

Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_221.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_222.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_223.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_224.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_225.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_226.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_227.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_228.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_229.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_230.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_231.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_232.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_233.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_234.wav
Processing: C:/AWC_Dataset/audio_files_preproces

Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_345.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_346.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_347.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_348.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_349.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_350.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_351.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_352.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_353.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_354.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_355.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_356.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_357.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/two/two_358.wav
Processing: C:/AWC_Dataset/audio_files_preproces

Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_67.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_68.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_69.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_70.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_71.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_72.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_73.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_74.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_75.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_76.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_77.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_78.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_79.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_80.wav
Proces

Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_184.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_185.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_186.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_187.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_188.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_189.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_190.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_191.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_192.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_193.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_194.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_195.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_196.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_

Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_298.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_299.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_300.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_301.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_302.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_303.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_304.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_305.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_306.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_307.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_308.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_309.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_310.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/three/three_

Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_14.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_15.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_16.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_17.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_18.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_19.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_20.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_21.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_22.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_23.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_24.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_25.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_26.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_27.wav
Processing: C:/AWC_Dataset/audio_f

Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_134.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_135.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_136.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_137.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_138.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_139.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_140.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_141.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_142.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_143.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_144.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_145.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_146.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_147.wav
Processing: C:/AWC_D

Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_255.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_256.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_257.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_258.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_259.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_260.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_261.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_262.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_263.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_264.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_265.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_266.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_267.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_268.wav
Processing: C:/AWC_D

Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_373.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_374.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_375.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_376.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_377.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_378.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_379.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_380.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_381.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_382.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_383.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_384.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_385.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/four/four_386.wav
Processing: C:/AWC_D

Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_97.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_98.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_99.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_100.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_101.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_102.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_103.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_104.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_105.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_106.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_107.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_108.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_109.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_110.wav
Processing: C:/AWC_Data

Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_216.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_217.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_218.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_219.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_220.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_221.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_222.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_223.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_224.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_225.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_226.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_227.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_228.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_229.wav
Processing: C:/AWC_D

Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_336.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_337.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_338.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_339.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_340.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_341.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_342.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_343.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_344.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_345.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_346.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_347.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_348.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/five/five_349.wav
Processing: C:/AWC_D

Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_55.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_56.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_57.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_58.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_59.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_60.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_61.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_62.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_63.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_64.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_65.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_66.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_67.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_68.wav
Processing: C:/AWC_Dataset/audio_f

Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_174.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_175.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_176.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_177.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_178.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_179.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_180.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_181.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_182.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_183.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_184.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_185.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_186.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_187.wav
Processing: C:/AWC_D

Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_296.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_297.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_298.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_299.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_300.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_301.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_302.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_303.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_304.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_305.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_306.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_307.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_308.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/grab/grab_309.wav
Processing: C:/AWC_D

Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_14.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_15.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_16.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_17.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_18.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_19.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_20.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_21.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_22.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_23.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_24.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_25.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_26.wav
Processing: C:/AWC_Datase

Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_124.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_125.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_126.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_127.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_128.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_129.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_130.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_131.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_132.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_133.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_134.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_135.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_136.wav
Processing: 

Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_234.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_235.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_236.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_237.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_238.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_239.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_240.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_241.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_242.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_243.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_244.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_245.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_246.wav
Processing: 

Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_343.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_344.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_345.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_346.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_347.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_348.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_349.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_350.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_351.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_352.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_353.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_354.wav
Processing: C:/AWC_Dataset/audio_files_preprocessed/release/release_355.wav
Processing: 

In [3]:
features
print(len(features))
print(features.shape)

2800
(2800, 39)


In [4]:
df = pd.DataFrame(features)

labels = ["one", "two", "three", "four", "five", "grab", "release"]
df['label'] = np.repeat(labels, 400)

csv_data= df.to_csv(r'C:/AWC_Dataset/STFT_MFCC_Final.csv'.format(i), mode='a', index=False)

In [5]:
df

0           1          2          3          4         5  \
0    -1066.209473   44.541866  34.394123   7.478784  -2.447765  6.216322   
1    -1049.811890   57.216091  37.946198   3.671708  -4.350953  8.842994   
2    -1020.075012   88.894608  59.334095  14.398818  -3.604246  3.938384   
3    -1035.225952   70.165619  48.452503  12.874611  -2.180924  3.799930   
4    -1043.581665   58.381897  41.012531   9.555207  -2.443362  6.004982   
...           ...         ...        ...        ...        ...       ...   
2795  -991.132568  106.346802  38.069279 -22.000553 -26.186035  2.752560   
2796 -1018.835632   85.085579  37.668362 -13.854801 -27.426426 -9.908359   
2797  -979.993347  120.619873  41.430489 -27.887060 -32.686996  2.761322   
2798  -983.474182  115.352654  41.468819 -24.599987 -29.525490  1.870099   
2799  -991.079468   96.930962  31.242479 -24.655745 -26.571552  4.933033   

              6          7          8          9  ...        30        31  \
0     14.752454  14.708940   6.762261   0.657862  ...  0.318491  2.848509   
1     19.957632  17.601740   4.962308  -3.545894  ... -3.417719 -1.708631   
2     12.475641   8.923004  -1.653559  -8.344602  ... -4.750584 -1.724951   
3     12.169857  11.654165   4.684117  -1.994266  ... -1.021690  2.661875   
4     15.333605  14.971415   7.316560  -0.705994  ... -0.800886  1.537163   
...         ...        ...        ...        ...  ...       ...       ...   
2795  22.433777  13.594213  -6.595747 -14.780283  ...  2.281338  1.015528   
2796   8.204995   9.879974   0.929106  -5.417086  ...  0.432221  1.671170   
2797  23.511717  11.686547 -12.507917 -19.293587  ...  3.829330  3.118210   
2798  22.493866  12.798771  -8.351742 -16.509249  ...  3.211800  2.241047   
2799  25.239738  17.290344  -3.309491 -12.918533  ...  3.478718  1.753865   

            32        33        34        35        36        37        38  \
0     3.622840  4.485036  2.514390  1.559597  1.801434  5.078111  5.435228   
1     0.903371  3.144014  3.456820  4.323700  4.894680  4.549000  2.524832   
2     1.665345  5.706401  5.163783  4.601019  3.275942  3.695179  3.850728   
3     5.716160  6.213809  3.327477  1.198997  0.413670  1.095415  2.971907   
4     4.786208  5.347678  2.429662  1.320515  0.643025  3.326674  4.679003   
...        ...       ...       ...       ...       ...       ...       ...   
2795 -1.564016 -2.736565 -1.894579  0.579743  2.406742  1.661522  0.187662   
2796  1.824791  1.965263  0.547279  1.570288  1.202643  1.937657  2.185189   
2797 -0.795803 -2.156904 -1.645986  1.966953  3.445284  2.765080  0.654372   
2798 -0.896646 -2.855199 -3.717281  0.147521  2.085273  2.193520  1.867288   
2799 -1.443522 -3.090092 -2.035834  1.746354  2.818180  3.455522  1.051455   

        label  
0         one  
1         one  
2         one  
3         one  
4         one  
...       ...  
2795  release  
2796  release  
2797  release  
2798  release  
2799  release  

[2800 rows x 40 columns]

In [6]:
X = df.iloc[:, :-1]  # selects all rows (:) and all but the last column (:-1) of the DataFrame df.
Y = df.iloc[:, -1]    #  selects all rows (:) and the last column (-1) of the DataFrame df.

# train test split
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, random_state=5)

In [7]:
X

0           1          2          3          4         5   \
0    -1066.209473   44.541866  34.394123   7.478784  -2.447765  6.216322   
1    -1049.811890   57.216091  37.946198   3.671708  -4.350953  8.842994   
2    -1020.075012   88.894608  59.334095  14.398818  -3.604246  3.938384   
3    -1035.225952   70.165619  48.452503  12.874611  -2.180924  3.799930   
4    -1043.581665   58.381897  41.012531   9.555207  -2.443362  6.004982   
...           ...         ...        ...        ...        ...       ...   
2795  -991.132568  106.346802  38.069279 -22.000553 -26.186035  2.752560   
2796 -1018.835632   85.085579  37.668362 -13.854801 -27.426426 -9.908359   
2797  -979.993347  120.619873  41.430489 -27.887060 -32.686996  2.761322   
2798  -983.474182  115.352654  41.468819 -24.599987 -29.525490  1.870099   
2799  -991.079468   96.930962  31.242479 -24.655745 -26.571552  4.933033   

             6          7          8          9   ...        29        30  \
0     14.752454  14.708940   6.762261   0.657862  ...  0.576264  0.318491   
1     19.957632  17.601740   4.962308  -3.545894  ... -3.188721 -3.417719   
2     12.475641   8.923004  -1.653559  -8.344602  ... -2.935563 -4.750584   
3     12.169857  11.654165   4.684117  -1.994266  ... -1.915084 -1.021690   
4     15.333605  14.971415   7.316560  -0.705994  ... -1.974954 -0.800886   
...         ...        ...        ...        ...  ...       ...       ...   
2795  22.433777  13.594213  -6.595747 -14.780283  ...  2.312015  2.281338   
2796   8.204995   9.879974   0.929106  -5.417086  ...  1.308392  0.432221   
2797  23.511717  11.686547 -12.507917 -19.293587  ...  1.540399  3.829330   
2798  22.493866  12.798771  -8.351742 -16.509249  ...  2.653898  3.211800   
2799  25.239738  17.290344  -3.309491 -12.918533  ...  2.906890  3.478718   

            31        32        33        34        35        36        37  \
0     2.848509  3.622840  4.485036  2.514390  1.559597  1.801434  5.078111   
1    -1.708631  0.903371  3.144014  3.456820  4.323700  4.894680  4.549000   
2    -1.724951  1.665345  5.706401  5.163783  4.601019  3.275942  3.695179   
3     2.661875  5.716160  6.213809  3.327477  1.198997  0.413670  1.095415   
4     1.537163  4.786208  5.347678  2.429662  1.320515  0.643025  3.326674   
...        ...       ...       ...       ...       ...       ...       ...   
2795  1.015528 -1.564016 -2.736565 -1.894579  0.579743  2.406742  1.661522   
2796  1.671170  1.824791  1.965263  0.547279  1.570288  1.202643  1.937657   
2797  3.118210 -0.795803 -2.156904 -1.645986  1.966953  3.445284  2.765080   
2798  2.241047 -0.896646 -2.855199 -3.717281  0.147521  2.085273  2.193520   
2799  1.753865 -1.443522 -3.090092 -2.035834  1.746354  2.818180  3.455522   

            38  
0     5.435228  
1     2.524832  
2     3.850728  
3     2.971907  
4     4.679003  
...        ...  
2795  0.187662  
2796  2.185189  
2797  0.654372  
2798  1.867288  
2799  1.051455  

[2800 rows x 39 columns]

In [8]:
Y

0           one
1           one
2           one
3           one
4           one
         ...   
2795    release
2796    release
2797    release
2798    release
2799    release
Name: label, Length: 2800, dtype: object

In [9]:
x_train

0           1          2          3          4         5   \
2698  -974.010376  116.250725  38.545593 -26.689840 -31.540546  2.354210   
589   -986.563904  114.152466  62.450790   0.750653 -17.960213 -0.564258   
208   -961.280579  123.127304  64.796883   3.910480 -14.765190  0.138902   
1246  -951.719055  145.340424  70.164185  -5.189845 -29.020164 -7.423698   
72    -955.162109  145.852997  77.814430   4.241280 -20.183451  0.022563   
...           ...         ...        ...        ...        ...       ...   
1032  -977.265625  117.950775  65.896545   3.358938 -19.939966 -9.718514   
2121 -1021.397461   71.714882  42.042854   4.460998  -4.887809  8.389032   
1424 -1050.274414   69.615501  47.300327   6.832437 -12.018888 -7.933200   
1725 -1006.033630   98.834503  48.380535  -9.979236 -26.320070 -8.952501   
2254  -959.247131  127.879173  54.621731 -18.710598 -37.223507 -6.831624   

             6          7          8          9   ...        29        30  \
2698  24.583941  17.053789  -6.451899 -16.423439  ...  1.444068  2.487337   
589   19.414585  19.900852   5.262323  -8.122587  ... -4.029535 -1.395275   
208   16.369293  12.159285  -1.663133 -10.454930  ... -3.376243 -0.524866   
1246  16.217880  18.852741   3.142623  -7.398784  ... -3.642962 -2.543337   
72    24.021809  26.024660  10.909758  -3.036780  ...  3.362832  4.356419   
...         ...        ...        ...        ...  ...       ...       ...   
1032   6.022215   7.086989  -2.426009  -9.309619  ...  4.525205  5.897151   
2121  21.131086  16.944777   3.360156  -4.137386  ... -0.555457 -0.886856   
1424   1.932329   3.820611  -1.101663  -7.135232  ... -2.514352 -1.447033   
1725   6.225140   2.870374  -9.671577 -13.393785  ... -4.980754 -0.341891   
2254  24.984324  29.516943  10.624717  -7.448892  ...  0.224855  0.909655   

            31        32        33        34        35        36        37  \
2698  2.660170  1.641031 -0.445350 -0.555491 -0.673474 -0.466091 -0.541337   
589   2.335118  0.486595 -1.439116 -2.909127 -1.820892 -0.900313  0.521147   
208   3.145987  4.499970  4.714534  1.884876  0.011687  0.361302  1.023096   
1246  1.334083  2.407800  3.220563  2.392077  0.813337 -1.146206 -2.517991   
72    4.426322  2.851455  2.215087  1.458462  2.694232  1.688161  1.779680   
...        ...       ...       ...       ...       ...       ...       ...   
1032  6.494415  1.438482 -1.622534 -3.881168 -1.740584  0.300715  2.443282   
2121 -0.656247 -0.293012  0.738061  0.362828  0.742804  0.557133 -0.460186   
1424  0.309976  0.521209  0.845885  0.833498  1.961323  2.361340  3.876053   
1725  2.012882 -0.006911 -1.871665 -0.486464  4.547205  6.434464  5.260001   
2254  1.595203 -0.146556 -0.327573 -0.324874  0.440832  1.276099  0.204917   

            38  
2698 -1.023764  
589   3.260086  
208   2.726993  
1246 -2.383617  
72   -0.213914  
...        ...  
1032  2.227825  
2121 -2.642147  
1424  2.741539  
1725  0.792575  
2254 -1.652587  

[2240 rows x 39 columns]

In [10]:
x_test

0           1          2          3          4          5   \
2114 -1022.669373   75.754227  44.221142   5.377441  -4.870851   8.899947   
883   -974.772095  125.322693  60.195969  -7.948168 -28.234348  -9.198785   
115   -932.718994  164.906708  80.055695  -5.643809 -32.301083  -6.816055   
12   -1061.217163   49.809948  40.983601  13.382963  -0.710442   1.742167   
430   -979.427307  129.618286  76.327843   9.443079 -15.965829  -1.337933   
...           ...         ...        ...        ...        ...        ...   
767   -931.046265  155.179214  65.322105 -21.143316 -43.646393 -13.864715   
71    -958.006409  141.281311  78.617538   7.960983 -17.120468  -0.151416   
2522  -887.902283  169.382446  52.699043 -38.259857 -47.309811  -4.386777   
2348  -930.923523  155.366272  73.296753  -8.271370 -32.542107  -8.200251   
2675  -981.287292  106.051247  34.444218 -25.147638 -28.827667   2.821421   

             6          7          8          9   ...        29        30  \
2114  19.593075  16.849548   4.528286  -4.100796  ...  0.046657  2.357319   
883    9.503967   6.878466  -7.512756 -14.155282  ...  1.693861  2.860141   
115   21.450079  24.395182   6.158950  -7.942114  ... -0.116935  0.614734   
12    10.734245  16.193556  15.133915  10.552652  ... -2.218669 -2.064589   
430   21.890770  26.886333  15.731512   2.831252  ...  3.604083  4.354414   
...         ...        ...        ...        ...  ...       ...       ...   
767   18.451895  23.764009   6.722630  -8.248211  ...  2.334926  3.450835   
71    23.111353  25.596935   9.882442  -5.046674  ...  1.701275  0.506773   
2522  26.925510  18.584995 -11.021029 -23.651922  ...  2.390319  3.199284   
2348  20.201090  22.365801   4.045171  -9.891442  ...  2.618324  2.700828   
2675  23.778557  15.747764  -4.643568 -13.374642  ...  2.003920  2.168559   

            31        32        33        34        35        36        37  \
2114  1.887276 -1.308403 -3.644236 -4.066503 -1.315594 -0.540244 -1.095859   
883   2.583277 -0.401410 -1.576226 -1.022617  0.559698  2.070908  0.834244   
115   1.905588  0.989441  1.619659  1.629357  1.997235  1.588566  1.203409   
12    0.033492  0.537099  1.078684 -0.239365 -1.973444 -1.915745 -2.177107   
430   3.141208  1.556828 -0.732162  0.326713  2.006872  3.133164  2.637815   
...        ...       ...       ...       ...       ...       ...       ...   
767   3.123955  1.161284 -0.896975 -2.274383 -0.907661  0.727680  1.950832   
71    2.071342  3.840286  4.113836  3.031161  1.605609  0.256869  0.249524   
2522  2.837459 -1.216810 -4.596735 -6.004311 -4.885569 -4.341630 -3.844731   
2348  1.659279 -3.183071 -4.672561 -5.858916 -3.171720 -1.401107  0.283747   
2675  2.790249  0.121804 -0.271325  0.609097  2.581407  1.237690 -0.598499   

            38  
2114 -2.467049  
883  -1.670036  
115   0.296791  
12   -2.241395  
430   0.705844  
...        ...  
767   1.423770  
71    1.711753  
2522 -4.581215  
2348 -0.980259  
2675 -1.693562  

[560 rows x 39 columns]

In [11]:
y_train

2698    release
589         two
208         one
1246       four
72          one
         ...   
1032      three
2121       grab
1424       four
1725       five
2254       grab
Name: label, Length: 2240, dtype: object

In [12]:
y_test

2114       grab
883       three
115         one
12          one
430         two
         ...   
767         two
71          one
2522    release
2348       grab
2675    release
Name: label, Length: 560, dtype: object

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

train_X = sc.fit_transform(x_train)
test_X = sc.transform(x_test)

In [14]:
train_X

array([[-0.02410448, -0.15011251, -1.3894355 , ..., -0.60735416,
        -0.7709428 , -0.5596057 ],
       [-0.3326966 , -0.21482608,  0.2557471 , ..., -0.7961199 ,
        -0.27263936,  1.4447718 ],
       [ 0.28882068,  0.06197191,  0.41720784, ..., -0.24766886,
        -0.03722585,  1.1953421 ],
       ...,
       [-1.8988347 , -1.5884154 , -0.7869249 , ...,  0.6217903 ,
         1.300808  ,  1.2021481 ],
       [-0.81130344, -0.6872559 , -0.7125838 , ...,  2.392464  ,
         1.9498779 ,  0.29024437],
       [ 0.33880708,  0.20852695, -0.28305763, ...,  0.15001266,
        -0.4209507 , -0.85382646]], dtype=float32)

In [15]:
test_X

array([[-1.2202449 , -1.3990875 , -0.99883795, ..., -0.63959026,
        -1.0310133 , -1.2349063 ],
       [-0.04282913,  0.12968111,  0.10056773, ...,  0.49553332,
        -0.12579697, -0.8619907 ],
       [ 0.9909244 ,  1.3505138 ,  1.4673367 , ...,  0.2858487 ,
         0.04734074,  0.05827096],
       ...,
       [ 2.0926135 ,  1.4885526 , -0.41537917, ..., -2.2921333 ,
        -2.3202312 , -2.224107  ],
       [ 1.0350609 ,  1.0562719 ,  1.0021785 , ..., -1.0138254 ,
        -0.38397968, -0.53924996],
       [-0.20298639, -0.46468028, -1.6716969 , ...,  0.13331565,
        -0.7977517 , -0.8729985 ]], dtype=float32)

### Decision Tree

In [16]:
from sklearn.metrics import accuracy_score
import joblib
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import sklearn.metrics as metrics
#Assign model with Decision Tree classifier

model_dt = DecisionTreeClassifier(max_depth=11)

model_dt.fit(x_train, y_train)

joblib.dump(model_dt,"./Trained_Models/Processed/model_dt")

y_pred1 = model_dt.predict(x_test)

print("Decision Tree")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
print("Train Accuracy:",model_dt.score(x_train, y_train))
print("Test Accuracy:",model_dt.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred1, pos_label='positive', average='micro')) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred1, pos_label='positive', average='micro', beta=2.0))
print("F1 Score: ",metrics.f1_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred1))

# print("ROC curve ", metrics.plot_roc_curve(model_dt,x_test, y_test))

Decision Tree
Decision Tree Accuracy:  91.60714285714285 %
Train Accuracy: 0.9799107142857143
Test Accuracy: 0.9160714285714285
Precision Score:  0.9160714285714285
Recall Score:  0.9160714285714285
F2 Score:  0.9160714285714285
F1 Score:  0.9160714285714285
Confusion Matrix: 
[[82  0  0  0  0  1  3]
 [ 0 65  1  1  0  0  3]
 [ 1  2 66  3  0  1  6]
 [ 0  0  1 71  0  0  4]
 [ 0  0  0  0 85  2  0]
 [ 0  1  1  1  0 76  3]
 [ 1  0  4  4  2  1 68]]


### Decision Tree - Hyperparameter Tuning

In [17]:
#Decision Tree Classifier 
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
import joblib
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import sklearn.metrics as metrics

# Define the hyperparameters to search over
param_grid = {
    'max_depth': [2, 4, 6, 9, 11],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [2, 4],
    'criterion': ['gini', 'entropy'],
    'splitter': ['best', 'random']
}

# Create a decision tree classifier object
dt = DecisionTreeClassifier()

#Assign model with Decision Tree classifier
model_dt = DecisionTreeClassifier()

# Perform grid search to find the best hyperparameters
grid_search = GridSearchCV(model_dt, param_grid, cv=5)
grid_search.fit(x_train, y_train)

# Print the best hyperparameters and the corresponding accuracy score
print("Best hyperparameters:", grid_search.best_params_)
print("Best accuracy:", grid_search.best_score_)

joblib.dump(grid_search,"./Trained_Models/Processed/model_dt_tuned")

#predicting the target variable using testing variables
y_pred1 = grid_search.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
print("Train Accuracy:",grid_search.score(x_train, y_train))
print("Test Accuracy:",grid_search.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred1, pos_label='positive', average='micro')) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred1, pos_label='positive', average='micro', beta=2.0))
print("F1 Score: ",metrics.f1_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred1))
# print("ROC curve ",metrics.plot_roc_curve(grid_search,x_test, y_test))

Best hyperparameters: {'criterion': 'entropy', 'max_depth': 11, 'min_samples_leaf': 2, 'min_samples_split': 2, 'splitter': 'best'}
Best accuracy: 0.9245535714285715
Decision Tree Results
Decision Tree Accuracy:  91.96428571428571 %
Train Accuracy: 0.9928571428571429
Test Accuracy: 0.9196428571428571
Precision Score:  0.9196428571428571
Recall Score:  0.9196428571428571
F2 Score:  0.9196428571428571
F1 Score:  0.9196428571428571
Confusion Matrix: 
[[84  0  0  0  2  0  0]
 [ 1 67  2  0  0  0  0]
 [ 1  1 71  4  0  1  1]
 [ 1  3  0 71  0  0  1]
 [ 1  0  2  0 83  0  1]
 [ 0  0  4  1  3 74  0]
 [ 0  1  7  5  0  2 65]]


### Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators = 6)

model_rf.fit(x_train, y_train)
joblib.dump(model_rf,"./Trained_Models/Processed/model_rf")

y_pred2 = model_rf.predict(x_test)
print("Random Forest")
print("Train Accuracy:",model_rf.score(x_train, y_train))
print("Test Accuracy:",model_rf.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred2, pos_label='po  sitive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred2,))
# print("ROC curve ",metrics.plot_roc_curve(model_rf,x_test, y_test))

Random Forest
Train Accuracy: 0.9991071428571429
Test Accuracy: 0.9392857142857143
Precision Score:  0.9392857142857143
Recall Score:  0.9392857142857143
F1 Score:  0.9392857142857143
Confusion Matrix: 
[[83  0  0  0  2  0  1]
 [ 0 66  2  2  0  0  0]
 [ 1  0 71  4  0  0  3]
 [ 1  0  0 75  0  0  0]
 [ 1  0  0  1 85  0  0]
 [ 0  0  0  1  3 78  0]
 [ 0  1  4  6  0  1 68]]


### Random Forest - Hyperparameter Tuning

In [19]:
#Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define the hyperparameters to search over
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [2, 4, 6],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy'],
    'max_features': ['sqrt', 'log2']
}

model_rf = RandomForestClassifier()


# Perform grid search to find the best hyperparameters
grid_search_rf = GridSearchCV(model_rf, param_grid, cv=5)
grid_search_rf.fit(x_train, y_train)


print("Best hyperparameters: ", grid_search_rf.best_params_)
print("Best score: ", grid_search_rf.best_score_)

joblib.dump(grid_search_rf,"./Trained_Models/Processed/model_rf_tuned")

y_pred2 = grid_search_rf.predict(x_test)
print("Random Forest Classifier")
print("Train Accuracy:",grid_search_rf.score(x_train, y_train))
print("Test Accuracy:",grid_search_rf.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred2,))
# print("ROC curve ",metrics.plot_roc_curve(grid_search_rf,x_test, y_test))

Best hyperparameters:  {'criterion': 'entropy', 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 50}
Best score:  0.959375
Random Forest Classifier
Train Accuracy: 0.9794642857142857
Test Accuracy: 0.95
Precision Score:  0.95
Recall Score:  0.95
F1 Score:  0.9500000000000001
Confusion Matrix: 
[[83  0  0  0  3  0  0]
 [ 1 66  3  0  0  0  0]
 [ 0  0 76  2  0  1  0]
 [ 0  1  2 73  0  0  0]
 [ 0  0  1  0 86  0  0]
 [ 0  0  0  0  1 79  2]
 [ 0  0  2  7  1  1 69]]


### KNN 

In [20]:
#KNN classifier
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors = 13)
model_knn.fit(x_train, y_train)


joblib.dump(model_knn,"./Trained_Models/Processed/model_knn")
y_pred3 = model_knn.predict(x_test)
print("KNN")
print("Train Accuracy:",model_knn.score(x_train, y_train))
print("Test Accuracy:",model_knn.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred3,))
# print("ROC curve ",metrics.plot_roc_curve(model_knn,x_test, y_test))

KNN
Train Accuracy: 0.9616071428571429
Test Accuracy: 0.9410714285714286
Precision Score:  0.9410714285714286
Recall Score:  0.9410714285714286
F1 Score:  0.9410714285714286
Confusion Matrix: 
[[84  0  0  0  2  0  0]
 [ 0 68  1  0  0  0  1]
 [ 5  0 69  2  0  0  3]
 [ 3  0  1 70  0  0  2]
 [ 4  0  0  0 83  0  0]
 [ 0  0  0  0  2 79  1]
 [ 0  1  1  2  0  2 74]]


### KNN - Hyperparameter Tuning

In [21]:
#KNN classifier
from sklearn.neighbors import KNeighborsClassifier

# Define the parameter grid to search over
param_grid = {'n_neighbors': [5, 7, 13, 17, 23]}

# Create a KNeighborsClassifier object
knn = KNeighborsClassifier()

# Perform a grid search over the parameter grid using 5-fold cross-validation
grid_search_knn = GridSearchCV(knn, param_grid, cv=5)

# Fit the grid search object to the training data
#model_knn.fit(x_train, y_train)
grid_search_knn.fit(x_train, y_train)

# Print the best hyperparameters and their corresponding score
print("Best hyperparameters: ", grid_search_knn.best_params_)
print("Best score: ", grid_search_knn.best_score_)

joblib.dump(grid_search_knn,"./Trained_Models/Processed/model_knn_tuned")

y_pred3 = grid_search_knn.predict(x_test)

print("KNN")
print("Train Accuracy:",grid_search_knn.score(x_train, y_train))
print("Test Accuracy:",grid_search_knn.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred3,))
# print("ROC curve ",metrics.plot_roc_curve(grid_search_knn,x_test, y_test))

Best hyperparameters:  {'n_neighbors': 5}
Best score:  0.9598214285714285
KNN
Train Accuracy: 0.98125
Test Accuracy: 0.9767857142857143
Precision Score:  0.9767857142857143
Recall Score:  0.9767857142857143
F1 Score:  0.9767857142857143
Confusion Matrix: 
[[86  0  0  0  0  0  0]
 [ 0 70  0  0  0  0  0]
 [ 3  0 75  0  0  0  1]
 [ 2  0  1 73  0  0  0]
 [ 0  0  0  0 87  0  0]
 [ 0  0  0  0  2 80  0]
 [ 0  0  1  1  0  2 76]]


### SVM

In [22]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Define SVM models with different kernels
svc_models = [
    SVC(kernel='linear'),
    SVC(kernel='poly', degree=2),
    SVC(kernel='poly', degree=3),
    SVC(kernel='rbf'),
    SVC(kernel='sigmoid')
]

# Train and evaluate SVM models
for svc in svc_models:
    svc.fit(x_train, y_train)
    accuracy = svc.score(x_test, y_test)
    print(f"{svc.kernel} kernel accuracy: {accuracy:.3f}")

linear kernel accuracy: 0.945
poly kernel accuracy: 0.389
poly kernel accuracy: 0.500
rbf kernel accuracy: 0.320
sigmoid kernel accuracy: 0.125


### Naive Bayes

In [23]:
#Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.model_selection import GridSearchCV

gnb = GaussianNB()

gnb.fit(x_train, y_train)

joblib.dump(gnb,"./Trained_Models/Processed/model_Naive_Bayes_Tuning")
y_pred3 = gnb.predict(x_test)
print("Naive Bayes")
print("Train Accuracy:",gnb.score(x_train, y_train))
print("Test Accuracy:",gnb.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred3,))
# print("ROC curve ",metrics.plot_roc_curve(grid_search_naive,x_test, y_test))

Naive Bayes
Train Accuracy: 0.8651785714285715
Test Accuracy: 0.8196428571428571
Precision Score:  0.8196428571428571
Recall Score:  0.8196428571428571
F1 Score:  0.8196428571428571
Confusion Matrix: 
[[57  0 12  2  2  0 13]
 [ 0 58  4  0  1  0  7]
 [ 0  1 64  5  0  0  9]
 [ 0  1  3 70  0  0  2]
 [ 0  0  0  0 83  4  0]
 [ 2  2  3  3  1 71  0]
 [ 0  8  4 12  0  0 56]]


### LGBM

In [24]:
import lightgbm as lgb
from lightgbm import LGBMClassifier
import re

def clean_column_name(column_name):
    return re.sub('[^A-Za-z0-9_]+', '', str(column_name))

newdf = df.rename(columns=clean_column_name)
 
nX = newdf.iloc[:, :-1]
nY = newdf.iloc[:, -1]

# train test split
nx_train, nx_test, ny_train, ny_test = train_test_split(nX, nY, train_size=0.8, random_state=5)


model_lgbm = LGBMClassifier()
model_lgbm.fit(nx_train, ny_train)
joblib.dump(model_lgbm,"./Trained_Models/Processed/model_lgbm")
pred = model_lgbm.predict(nx_test)
print("LGBM")
print("Train Accuracy:",model_lgbm.score(nx_train, ny_train))
print("Test Accuracy:",model_lgbm.score(nx_test, ny_test))
print("Precision Score: ",metrics.precision_score(ny_test, pred, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(ny_test, pred, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(ny_test, pred, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(ny_test, pred,))
# print("ROC curve ",metrics.plot_roc_curve(model_lgbm, nx_test, ny_test))

LGBM
Train Accuracy: 1.0
Test Accuracy: 0.9803571428571428
Precision Score:  0.9803571428571428
Recall Score:  0.9803571428571428
F1 Score:  0.9803571428571428
Confusion Matrix: 
[[85  0  0  0  1  0  0]
 [ 0 68  1  0  0  0  1]
 [ 0  0 79  0  0  0  0]
 [ 1  0  0 75  0  0  0]
 [ 2  0  0  0 85  0  0]
 [ 2  0  0  0  0 79  1]
 [ 0  1  0  1  0  0 78]]


### Prediction

In [25]:
def extract_features(audio_file):
    audio, _ = librosa.load(audio_file, sr=sampling_rate)

    stft = np.abs(librosa.stft(audio, n_fft=n_fft, hop_length=hop_length))
    mfcc = librosa.feature.mfcc(S=librosa.power_to_db(stft), n_mfcc=n_mfcc)

    # Calculate the mean of each MFCC coefficient across all frames
    mfcc_mean = np.mean(mfcc, axis=1)
    
    return mfcc_mean

In [26]:
def audio_out(predicted_label):
    engine = pyttsx3.init()
    
    engine.setProperty('rate', 150)
    
    engine.setProperty('volume', 0.8)
    
    engine.say(predicted_label)
    
    engine.runAndWait()

In [27]:
model= joblib.load('./Trained_Models/Processed/model_Naive_Bayes_Tuning')

file_path = 'C:/AWC_Dataset/audio_files_preprocessed/three/three_9.wav'

class_labels = ["one", "two", "three", "four", "five", "grab", "release"]

feature_vector = extract_features(file_path)

feature_vector = feature_vector.reshape(1, -1)

model_proba = model.predict_proba(feature_vector)
predicted_index = model_proba.argmax()

predicted_label = class_labels[predicted_index]

print(predicted_label)

audio_out(predicted_label)

three


In [28]:
model_proba

array([[7.46885858e-13, 1.01551339e-10, 9.62287347e-01, 2.11132728e-08,
        1.62075470e-04, 3.75418137e-02, 8.74299233e-06]])